/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

/**
 *
 * @author a24borjapp
 */
public class ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventana.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public ventana() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textPrimerNumero = new javax.swing.JTextField();
        botonResta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textResultado = new javax.swing.JTextField();
        botonSuma = new javax.swing.JButton();
        botonBorrao = new javax.swing.JButton();
        botonMultli = new javax.swing.JButton();
        botonDivision = new javax.swing.JButton();
        botonElevado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Bot1 = new javax.swing.JButton();
        Bot2 = new javax.swing.JButton();
        Bot3 = new javax.swing.JButton();
        Bot4 = new javax.swing.JButton();
        Bot5 = new javax.swing.JButton();
        Bot7 = new javax.swing.JButton();
        Bot8 = new javax.swing.JButton();
        Bot9 = new javax.swing.JButton();
        Bot0 = new javax.swing.JButton();
        Bot6 = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Operacion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));

        textPrimerNumero.setBackground(new java.awt.Color(51, 51, 0));
        textPrimerNumero.setForeground(new java.awt.Color(0, 204, 204));

        botonResta.setBackground(new java.awt.Color(51, 255, 102));
        botonResta.setForeground(new java.awt.Color(0, 51, 255));
        botonResta.setText("-");
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Resultado:");

        textResultado.setBackground(new java.awt.Color(51, 51, 0));
        textResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textResultado.setForeground(new java.awt.Color(0, 204, 204));
        textResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textResultadoActionPerformed(evt);
            }
        });

        botonSuma.setBackground(new java.awt.Color(51, 255, 102));
        botonSuma.setForeground(new java.awt.Color(0, 51, 255));
        botonSuma.setText("+");
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });

        botonBorrao.setBackground(new java.awt.Color(51, 255, 102));
        botonBorrao.setForeground(new java.awt.Color(0, 51, 255));
        botonBorrao.setText("Del");
        botonBorrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorraoActionPerformed(evt);
            }
        });

        botonMultli.setBackground(new java.awt.Color(51, 255, 102));
        botonMultli.setForeground(new java.awt.Color(0, 51, 255));
        botonMultli.setText("*");
        botonMultli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultliActionPerformed(evt);
            }
        });

        botonDivision.setBackground(new java.awt.Color(51, 255, 102));
        botonDivision.setForeground(new java.awt.Color(0, 51, 255));
        botonDivision.setText("/");
        botonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivisionActionPerformed(evt);
            }
        });

        botonElevado.setBackground(new java.awt.Color(51, 255, 102));
        botonElevado.setForeground(new java.awt.Color(0, 51, 255));
        botonElevado.setText("^");
        botonElevado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElevadoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Calculadora");

        Bot1.setText("1");
        Bot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot1ActionPerformed(evt);
            }
        });

        Bot2.setText("2");
        Bot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot2ActionPerformed(evt);
            }
        });

        Bot3.setText("3");
        Bot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot3ActionPerformed(evt);
            }
        });

        Bot4.setText("4");
        Bot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot4ActionPerformed(evt);
            }
        });

        Bot5.setText("5");
        Bot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot5ActionPerformed(evt);
            }
        });

        Bot7.setText("7");
        Bot7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot7ActionPerformed(evt);
            }
        });

        Bot8.setText("8");
        Bot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot8ActionPerformed(evt);
            }
        });

        Bot9.setText("9");
        Bot9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot9ActionPerformed(evt);
            }
        });

        Bot0.setText("0");
        Bot0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot0ActionPerformed(evt);
            }
        });

        Bot6.setText("6");
        Bot6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot6ActionPerformed(evt);
            }
        });

        BotonIgual.setText("Roblox");
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Bot6)
                                    .addComponent(Bot1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Bot2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Bot3)
                                        .addGap(18, 18, 18)
                                        .addComponent(Bot4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Bot7)
                                        .addGap(18, 18, 18)
                                        .addComponent(Bot8)
                                        .addGap(18, 18, 18)
                                        .addComponent(Bot9)))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bot5)
                                    .addComponent(Bot0))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(textPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(185, 185, 185))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addComponent(botonBorrao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(665, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonIgual))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonDivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonElevado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonMultli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Bot1)
                                    .addComponent(Bot2)
                                    .addComponent(Bot3)
                                    .addComponent(Bot4)
                                    .addComponent(Bot5))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonMultli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bot6)
                            .addComponent(Bot7)
                            .addComponent(Bot8)
                            .addComponent(Bot9)
                            .addComponent(Bot0)
                            .addComponent(botonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonElevado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonIgual, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)))
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonBorrao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String segundoNumero="";
    char operacion;
    public  int resultado=0;
    private void resInicial(){
    if(resultado==0)this.resultado=Integer.parseInt(segundoNumero);
}
    private void textResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textResultadoActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        resInicial();
        getOperacion();
        segundoNumero="";
        operacion='-';
        textPrimerNumero.setText(textPrimerNumero.getText()+"-");                                  
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        resInicial();
        getOperacion();
        segundoNumero="";
        operacion='+';
        textPrimerNumero.setText(textPrimerNumero.getText()+"+");                                  
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonBorraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorraoActionPerformed
 
        segundoNumero=""; 
        resultado=0;
        textPrimerNumero.setText(""); 
        textResultado.setText("");
    }//GEN-LAST:event_botonBorraoActionPerformed

    private void botonMultliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultliActionPerformed
        resInicial();
        getOperacion();
        segundoNumero=""; 
        operacion='*';
        textPrimerNumero.setText(textPrimerNumero.getText()+"*");                                  
    }//GEN-LAST:event_botonMultliActionPerformed

    private void botonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivisionActionPerformed
        resInicial();
        getOperacion();  
        segundoNumero=""; 
        operacion='/';
        textPrimerNumero.setText(textPrimerNumero.getText()+"/");                                  
    }//GEN-LAST:event_botonDivisionActionPerformed

    private void botonElevadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElevadoActionPerformed
           segundoNumero="";
        textPrimerNumero.setText(textPrimerNumero.getText()+"+");                                  
    }//GEN-LAST:event_botonElevadoActionPerformed

    private void Bot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot2ActionPerformed
        segundoNumero=segundoNumero+"2";
        textPrimerNumero.setText(textPrimerNumero.getText()+2);    }//GEN-LAST:event_Bot2ActionPerformed

    private void Bot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot4ActionPerformed
       segundoNumero=segundoNumero+"4";
        textPrimerNumero.setText(textPrimerNumero.getText()+4);
    }//GEN-LAST:event_Bot4ActionPerformed

    private void Bot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot1ActionPerformed
        segundoNumero=segundoNumero+"1";
        textPrimerNumero.setText(textPrimerNumero.getText()+1);
    }//GEN-LAST:event_Bot1ActionPerformed

    private void Bot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot3ActionPerformed
        segundoNumero=segundoNumero+"3";
        textPrimerNumero.setText(textPrimerNumero.getText()+3);    }//GEN-LAST:event_Bot3ActionPerformed

    private void Bot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot5ActionPerformed
        segundoNumero=segundoNumero+"5";
        textPrimerNumero.setText(textPrimerNumero.getText()+5);

    }//GEN-LAST:event_Bot5ActionPerformed

    private void Bot6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot6ActionPerformed
        segundoNumero=segundoNumero+"6";
        textPrimerNumero.setText(textPrimerNumero.getText()+6);

    }//GEN-LAST:event_Bot6ActionPerformed

    private void Bot7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot7ActionPerformed
        segundoNumero=segundoNumero+"7";
        textPrimerNumero.setText(textPrimerNumero.getText()+7);

    }//GEN-LAST:event_Bot7ActionPerformed

    private void Bot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot8ActionPerformed
        segundoNumero=segundoNumero+"8";
        textPrimerNumero.setText(textPrimerNumero.getText()+8);

    }//GEN-LAST:event_Bot8ActionPerformed

    private void Bot9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot9ActionPerformed
        segundoNumero=segundoNumero+"9";
        textPrimerNumero.setText(textPrimerNumero.getText()+9);
    }//GEN-LAST:event_Bot9ActionPerformed

    private void Bot0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot0ActionPerformed
       if(textPrimerNumero.getText().charAt(textPrimerNumero.getText().length()-1) =='/'){
      dialogo ventana_dialogo=new dialogo(this,true);
      ventana_dialogo.setLocationRelativeTo(this);
      ventana_dialogo.setVisible(true);
       }
      else{textPrimerNumero.setText(textPrimerNumero.getText()+0); segundoNumero=segundoNumero+0;}    }//GEN-LAST:event_Bot0ActionPerformed
      
    private void getOperacion(){
         switch(operacion){
            case '+':this.resultado+=Integer.parseInt(segundoNumero);break;
            case '-':this.resultado-=Integer.parseInt(segundoNumero);break;
            case '*':this.resultado*=Integer.parseInt(segundoNumero);break;
            case '/':this.resultado/=Integer.parseInt(segundoNumero);break;
            default:break;
        }
        
    }
    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
           getOperacion();
        textResultado.setText("resultado :"+this.resultado);
    }//GEN-LAST:event_BotonIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bot0;
    private javax.swing.JButton Bot1;
    private javax.swing.JButton Bot2;
    private javax.swing.JButton Bot3;
    private javax.swing.JButton Bot4;
    private javax.swing.JButton Bot5;
    private javax.swing.JButton Bot6;
    private javax.swing.JButton Bot7;
    private javax.swing.JButton Bot8;
    private javax.swing.JButton Bot9;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton botonBorrao;
    private javax.swing.JButton botonDivision;
    private javax.swing.JButton botonElevado;
    private javax.swing.JButton botonMultli;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textPrimerNumero;
    private javax.swing.JTextField textResultado;
    // End of variables declaration//GEN-END:variables
}
