/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/**
 *
 * @author a24borjapp
 */
public class SelectorHora extends javax.swing.JPanel {
   private int hora;
   private int minutos;
   private PropertyChangeSupport notificador;

   public int getHora(){
       return hora;
   }
   
   public int getMinutos(){
       return minutos;
   }
   
   public void setHora(int hora){
       if (hora < 0 || hora > 23) {
           throw new IllegalArgumentException("La hora debe estar entre 0 y 23");
        }
        int horaAnterior = this.hora;
        this.hora=hora;
        if ((int) spHora.getValue() != hora) {
            spHora.setValue(hora);
        }    
        notificador.firePropertyChange("hora", horaAnterior,this.hora);
   }
   
    public void setMinutos(int minutos){
        if (hora < 0 || hora > 59) {
           throw new IllegalArgumentException("Los minutos debe estar entre 0 y 59");
        }
        int minutoAnterior = this.minutos;

        this.minutos=minutos;
        if ((int) spMinutos.getValue() != minutos) {
        spMinutos.setValue(minutos);
        }
        notificador.firePropertyChange("minuto", minutoAnterior,this.minutos);
  
   }
    /**
     * Creates new form NewJPanel
     */
    public SelectorHora() {
        initComponents();
        notificador=new PropertyChangeSupport(this);
        configurarListenersDeUsuario();
    }
    
 private void configurarListenersDeUsuario() {
    // Cuando el usuario cambia el spinner de hora
       spHora.addChangeListener(e -> {
       int horaSeleccionada = (int) spHora.getValue();
       setHora(horaSeleccionada);
       });
       // Cuando el usuario cambia el spinner de minutos
       spMinutos.addChangeListener(e -> {
       int minutoSeleccionado = (int) spMinutos.getValue();
       setMinutos(minutoSeleccionado);
       });
    }
 
        // Para suscribirse a TODOS los cambios
    public void agregarOyente(PropertyChangeListener oyente) {
     notificador.addPropertyChangeListener(oyente);
    }
    // Para suscribirse a los cambios de una propiedad concreta
    public void agregarOyentePropiedad(String propiedad,PropertyChangeListener oyente) {
     notificador.addPropertyChangeListener(propiedad, oyente);
    }
    // Para darse de baja de la suscripción
    public void eliminarOyente(PropertyChangeListener oyente) {
     notificador.removePropertyChangeListener(oyente);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spHora = new javax.swing.JSpinner();
        spMinutos = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        spHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spMinutos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spHora, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spHora)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(spMinutos)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner spHora;
    private javax.swing.JSpinner spMinutos;
    // End of variables declaration//GEN-END:variables
}
