/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rellena_informacion;

/**
 *
 * @author a24borjapp
 */
public class pagina extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pagina.class.getName());

    /**
     * Creates new form pagina
     */
    public pagina() {
        initComponents();
        RBAsistentesNo.setActionCommand("no");
        RBAsistentesSi.setActionCommand("si");
        RBBarNo.setActionCommand("no");
        RBBarSi.setActionCommand("si");
        RBEscapeNo.setActionCommand("no");
        RBEscapeSi.setActionCommand("si");
        RBCateringBuffet.setActionCommand("buffet");
        RBCateringChef.setActionCommand("chef");
        RBCateringMenu.setActionCommand("menu");      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDeCatering = new javax.swing.ButtonGroup();
        GrupoAsistentes = new javax.swing.ButtonGroup();
        GrupoEscape = new javax.swing.ButtonGroup();
        GrupoBar = new javax.swing.ButtonGroup();
        menu = new javax.swing.JTabbedPane();
        DatosCliente = new javax.swing.JPanel();
        LableApellido2 = new javax.swing.JLabel();
        LableNombre = new javax.swing.JLabel();
        LableApellido1 = new javax.swing.JLabel();
        LableTelefono = new javax.swing.JLabel();
        FieldApellido2 = new javax.swing.JTextField();
        FieldApellido1 = new javax.swing.JTextField();
        FieldNombre = new javax.swing.JTextField();
        FormatedFieldTelefono = new javax.swing.JFormattedTextField();
        DatosBoda = new javax.swing.JPanel();
        LableFecha = new javax.swing.JLabel();
        LablePresupuesto = new javax.swing.JLabel();
        LableNInvitados = new javax.swing.JLabel();
        LableTipoCatering = new javax.swing.JLabel();
        LabelAsistentes = new javax.swing.JLabel();
        LabelEscape = new javax.swing.JLabel();
        LabelBar = new javax.swing.JLabel();
        FormatedFieldFecha = new javax.swing.JFormattedTextField();
        ComboBoxPresupuesto = new javax.swing.JComboBox<>();
        FormatedFieldNInvitados = new javax.swing.JFormattedTextField();
        RBCateringMenu = new javax.swing.JRadioButton();
        RBCateringChef = new javax.swing.JRadioButton();
        RBCateringBuffet = new javax.swing.JRadioButton();
        RBAsistentesSi = new javax.swing.JRadioButton();
        RBAsistentesNo = new javax.swing.JRadioButton();
        RBEscapeSi = new javax.swing.JRadioButton();
        RBEscapeNo = new javax.swing.JRadioButton();
        RBBarSi = new javax.swing.JRadioButton();
        RBBarNo = new javax.swing.JRadioButton();
        BotonGuardar = new javax.swing.JButton();
        Resultado = new javax.swing.JPanel();
        ResLableApellido3 = new javax.swing.JLabel();
        ResLableNombre1 = new javax.swing.JLabel();
        ResLabelAsistentes1 = new javax.swing.JLabel();
        ResLablePresupuesto1 = new javax.swing.JLabel();
        ResLableApellido4 = new javax.swing.JLabel();
        ResLableTipoCatering1 = new javax.swing.JLabel();
        ResTextBar = new javax.swing.JTextField();
        ResTextEscape = new javax.swing.JTextField();
        ResTextAsistentes = new javax.swing.JTextField();
        ResTextCatering = new javax.swing.JTextField();
        ResTextInvitados = new javax.swing.JTextField();
        ResTextPresupuesto = new javax.swing.JTextField();
        ResTextFecha = new javax.swing.JTextField();
        ResTextNumeroTel = new javax.swing.JTextField();
        ResTextApellido2 = new javax.swing.JTextField();
        ResTextApellido1 = new javax.swing.JTextField();
        ResTextNombre = new javax.swing.JTextField();
        ResLableNInvitados1 = new javax.swing.JLabel();
        ResLableTelefono1 = new javax.swing.JLabel();
        ResLabelEscape1 = new javax.swing.JLabel();
        ResLabelBar1 = new javax.swing.JLabel();
        ResLableFecha1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reserva Voda");
        setBackground(new java.awt.Color(0, 102, 102));

        menu.setBackground(new java.awt.Color(255, 204, 204));
        menu.setForeground(new java.awt.Color(0, 0, 0));

        DatosCliente.setBackground(new java.awt.Color(0, 153, 153));

        LableApellido2.setText("Apellido2");

        LableNombre.setText("Nombre");

        LableApellido1.setText("Apellido1");

        LableTelefono.setText("NumTel");

        FieldApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldApellido2ActionPerformed(evt);
            }
        });

        FieldApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldApellido1ActionPerformed(evt);
            }
        });

        FieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNombreActionPerformed(evt);
            }
        });

        FormatedFieldTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FormatedFieldTelefono.setText("introduce numero telefono");

        javax.swing.GroupLayout DatosClienteLayout = new javax.swing.GroupLayout(DatosCliente);
        DatosCliente.setLayout(DatosClienteLayout);
        DatosClienteLayout.setHorizontalGroup(
            DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosClienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LableTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LableApellido2)
                    .addComponent(LableApellido1)
                    .addComponent(LableNombre))
                .addGap(32, 32, 32)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldNombre)
                    .addComponent(FieldApellido1)
                    .addComponent(FieldApellido2)
                    .addComponent(FormatedFieldTelefono))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        DatosClienteLayout.setVerticalGroup(
            DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosClienteLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LableNombre)
                    .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LableApellido1)
                    .addComponent(FieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LableApellido2))
                .addGap(65, 65, 65)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LableTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FormatedFieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );

        menu.addTab("Datos personales", DatosCliente);

        DatosBoda.setBackground(new java.awt.Color(0, 153, 153));

        LableFecha.setText("Fecha voda");

        LablePresupuesto.setText("Presupuestos voda");

        LableNInvitados.setText("Numero invitados");

        LableTipoCatering.setText("Tipo de servicio catering");

        LabelAsistentes.setText("Habitaciones para asistentes");

        LabelEscape.setText("Ruta de escape?");

        LabelBar.setText("bar libre?");

        FormatedFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        FormatedFieldFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormatedFieldFechaActionPerformed(evt);
            }
        });

        ComboBoxPresupuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "menos de 1000", "entre1000 y 2000", "entre 2000 y 3000", "mas de 3000" }));
        ComboBoxPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPresupuestoActionPerformed(evt);
            }
        });

        FormatedFieldNInvitados.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        GrupoDeCatering.add(RBCateringMenu);
        RBCateringMenu.setText("menú establecido");

        GrupoDeCatering.add(RBCateringChef);
        RBCateringChef.setText("negociación con el chef");

        GrupoDeCatering.add(RBCateringBuffet);
        RBCateringBuffet.setText("buffet");

        GrupoAsistentes.add(RBAsistentesSi);
        RBAsistentesSi.setText("si");

        GrupoAsistentes.add(RBAsistentesNo);
        RBAsistentesNo.setText("no");

        GrupoEscape.add(RBEscapeSi);
        RBEscapeSi.setText("si");

        GrupoEscape.add(RBEscapeNo);
        RBEscapeNo.setText("no");

        GrupoBar.add(RBBarSi);
        RBBarSi.setText("si");

        GrupoBar.add(RBBarNo);
        RBBarNo.setText("no");

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatosBodaLayout = new javax.swing.GroupLayout(DatosBoda);
        DatosBoda.setLayout(DatosBodaLayout);
        DatosBodaLayout.setHorizontalGroup(
            DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosBodaLayout.createSequentialGroup()
                .addComponent(RBCateringMenu)
                .addGap(18, 18, 18)
                .addComponent(RBCateringBuffet)
                .addGap(18, 18, 18)
                .addComponent(RBCateringChef)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosBodaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(DatosBodaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosBodaLayout.createSequentialGroup()
                        .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelAsistentes)
                            .addComponent(LabelEscape)
                            .addComponent(LableTipoCatering)
                            .addComponent(LabelBar)
                            .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(DatosBodaLayout.createSequentialGroup()
                                    .addComponent(RBBarSi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RBBarNo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DatosBodaLayout.createSequentialGroup()
                                    .addComponent(RBEscapeSi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RBEscapeNo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DatosBodaLayout.createSequentialGroup()
                                    .addComponent(RBAsistentesSi)
                                    .addGap(50, 50, 50)
                                    .addComponent(RBAsistentesNo))))
                        .addContainerGap(272, Short.MAX_VALUE))
                    .addGroup(DatosBodaLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableFecha)
                            .addComponent(FormatedFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LablePresupuesto))
                        .addGap(35, 35, 35)
                        .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableNInvitados)
                            .addComponent(FormatedFieldNInvitados, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        DatosBodaLayout.setVerticalGroup(
            DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosBodaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LableFecha)
                    .addComponent(LablePresupuesto)
                    .addComponent(LableNInvitados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormatedFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormatedFieldNInvitados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(LableTipoCatering)
                .addGap(27, 27, 27)
                .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBCateringMenu)
                    .addComponent(RBCateringBuffet)
                    .addComponent(RBCateringChef))
                .addGap(18, 18, 18)
                .addComponent(LabelAsistentes)
                .addGap(18, 18, 18)
                .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBAsistentesSi)
                    .addComponent(RBAsistentesNo))
                .addGap(18, 18, 18)
                .addComponent(LabelEscape)
                .addGap(18, 18, 18)
                .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBEscapeSi)
                    .addComponent(RBEscapeNo))
                .addGap(18, 18, 18)
                .addComponent(LabelBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBarSi)
                    .addComponent(RBBarNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.addTab("Datos boda", DatosBoda);

        Resultado.setBackground(new java.awt.Color(0, 153, 153));

        ResLableApellido3.setText("Apellido1");

        ResLableNombre1.setText("Nombre");

        ResLabelAsistentes1.setText("Habitaciones para asistentes");

        ResLablePresupuesto1.setText("Presupuestos voda");

        ResLableApellido4.setText("Apellido2");

        ResLableTipoCatering1.setText("Tipo de servicio catering");

        ResLableNInvitados1.setText("Numero invitados");

        ResLableTelefono1.setText("NumTel");

        ResLabelEscape1.setText("Ruta de escape?");

        ResLabelBar1.setText("bar libre?");

        ResLableFecha1.setText("Fecha voda");

        javax.swing.GroupLayout ResultadoLayout = new javax.swing.GroupLayout(Resultado);
        Resultado.setLayout(ResultadoLayout);
        ResultadoLayout.setHorizontalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(ResLablePresupuesto1)
                        .addGap(18, 18, 18)
                        .addComponent(ResTextPresupuesto))
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(ResLableNInvitados1)
                        .addGap(18, 18, 18)
                        .addComponent(ResTextInvitados))
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResLableNombre1)
                            .addComponent(ResLableApellido3)
                            .addComponent(ResLableApellido4)
                            .addComponent(ResLableTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResLableFecha1))
                        .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultadoLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(ResTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ResultadoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ResTextNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addComponent(ResTextApellido1)
                                        .addComponent(ResTextApellido2))
                                    .addComponent(ResTextNumeroTel)))))
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(ResLableTipoCatering1)
                        .addGap(32, 32, 32)
                        .addComponent(ResTextCatering))
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(ResLabelAsistentes1)
                        .addGap(18, 18, 18)
                        .addComponent(ResTextAsistentes, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(ResLabelBar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResTextBar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(ResLabelEscape1)
                        .addGap(52, 52, 52)
                        .addComponent(ResTextEscape)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        ResultadoLayout.setVerticalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultadoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLableNombre1)
                    .addComponent(ResTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLableApellido3)
                    .addComponent(ResTextApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLableApellido4)
                    .addComponent(ResTextApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLableTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResTextNumeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLableFecha1)
                    .addComponent(ResTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLablePresupuesto1)
                    .addComponent(ResTextPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLableNInvitados1)
                    .addComponent(ResTextInvitados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLableTipoCatering1)
                    .addComponent(ResTextCatering, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLabelAsistentes1)
                    .addComponent(ResTextAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResLabelEscape1)
                    .addComponent(ResTextEscape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResLabelBar1)
                    .addComponent(ResTextBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        menu.addTab("resultados", Resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNombreActionPerformed

    private void FieldApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldApellido1ActionPerformed

    private void FieldApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldApellido2ActionPerformed

    private void FormatedFieldFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormatedFieldFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormatedFieldFechaActionPerformed

    private void ComboBoxPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPresupuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxPresupuestoActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed

      DialogoBueno dialogoBueno=new DialogoBueno(this,true);
      dialogoBueno.setLocationRelativeTo(this);
      dialogoBueno.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pagina().setVisible(true));
    }

    public static void setResTextNombre(String nombre){
    ResTextNombre.setText(nombre);
    }
    public static void setResTextApellido1(String apell){
    ResTextApellido1.setText(apell);
    }
    public static void setResTextApellido2(String apell){
    ResTextApellido2.setText(apell);
    }
    public static void setResTextAsistentes(String asis){
    ResTextAsistentes.setText(asis);
    }
    public static void setResTextNumeroTel(String num){
    ResTextNumeroTel.setText(num);
    }
    public static void setResTextPresupuesto(String pres){
    ResTextPresupuesto.setText(pres);
    }
    public static void setResTextInvitado(String inv){
    ResTextInvitados.setText(inv);
    }
    public static void setResTextFecha(String fech){
    ResTextFecha.setText(fech);
    }
    public static void setResTextEscape(String esc){
    ResTextEscape.setText(esc);
    }
    public static void setResTextCatering(String cat){
    ResTextCatering.setText(cat);
    }
    public static void setResTextBar(String bar){
    ResTextBar.setText(bar);
    }
   
    public static String getFieldNombre(){
    return FieldNombre.getText(); 
    }
    public static String getFieldApellido1(){
    return FieldApellido1.getText(); 
    }
    public static String getFieldApellido2(){
    return FieldApellido2.getText(); 
    }
    public static String getFormatedFieldFecha(){
    return FormatedFieldFecha.getText(); 
    }
    public static String getFormatedFieldNInvitados(){
    return FormatedFieldNInvitados.getText(); 
    }
    public static String getFormatedFieldTelefono(){
    return FormatedFieldTelefono.getText(); 
    }
    public static String getGrupoAsistentes(){
        try{
            
    return GrupoAsistentes.getSelection().getActionCommand(); 
     
        }catch(NullPointerException e){
            System.out.println(" aun no se selecciono una opcion de asistentes");
        return "";
        }
    }
    public static String getGrupoBar(){
        try{
            
    return GrupoBar.getSelection().getActionCommand();
     
        }catch(NullPointerException e){
            System.out.println(" aun no se selecciono una opcion de Bar");
        return "";
        }
    }
    public static String getGrupoDeCatering(){
        try{
            
    return GrupoDeCatering.getSelection().getActionCommand();
        
        }catch(NullPointerException e){
            System.out.println(" aun no se selecciono una opcion de catering");
        return "";
        }
    }
    public static String getGrupoEscape(){
     try{
         
    return GrupoEscape.getSelection().getActionCommand();
     
        }catch(NullPointerException e){
            System.out.println(" aun no se selecciono una opcion de escape");
        return "";
        }
    }
    public static String getComboBoxPresupuesto(){
    return ComboBoxPresupuesto.getSelectedItem().toString(); 
    }
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private static javax.swing.JComboBox<String> ComboBoxPresupuesto;
    private javax.swing.JPanel DatosBoda;
    private javax.swing.JPanel DatosCliente;
    private static javax.swing.JTextField FieldApellido1;
    private static javax.swing.JTextField FieldApellido2;
    private static javax.swing.JTextField FieldNombre;
    private static javax.swing.JFormattedTextField FormatedFieldFecha;
    private static javax.swing.JFormattedTextField FormatedFieldNInvitados;
    private static javax.swing.JFormattedTextField FormatedFieldTelefono;
    private static javax.swing.ButtonGroup GrupoAsistentes;
    private static javax.swing.ButtonGroup GrupoBar;
    private static javax.swing.ButtonGroup GrupoDeCatering;
    private static javax.swing.ButtonGroup GrupoEscape;
    private javax.swing.JLabel LabelAsistentes;
    private javax.swing.JLabel LabelBar;
    private javax.swing.JLabel LabelEscape;
    private javax.swing.JLabel LableApellido1;
    private javax.swing.JLabel LableApellido2;
    private javax.swing.JLabel LableFecha;
    private javax.swing.JLabel LableNInvitados;
    private javax.swing.JLabel LableNombre;
    private javax.swing.JLabel LablePresupuesto;
    private javax.swing.JLabel LableTelefono;
    private javax.swing.JLabel LableTipoCatering;
    private javax.swing.JRadioButton RBAsistentesNo;
    private javax.swing.JRadioButton RBAsistentesSi;
    private javax.swing.JRadioButton RBBarNo;
    private javax.swing.JRadioButton RBBarSi;
    private javax.swing.JRadioButton RBCateringBuffet;
    private javax.swing.JRadioButton RBCateringChef;
    private javax.swing.JRadioButton RBCateringMenu;
    private javax.swing.JRadioButton RBEscapeNo;
    private javax.swing.JRadioButton RBEscapeSi;
    private javax.swing.JLabel ResLabelAsistentes1;
    private javax.swing.JLabel ResLabelBar1;
    private javax.swing.JLabel ResLabelEscape1;
    private javax.swing.JLabel ResLableApellido3;
    private javax.swing.JLabel ResLableApellido4;
    private javax.swing.JLabel ResLableFecha1;
    private javax.swing.JLabel ResLableNInvitados1;
    private javax.swing.JLabel ResLableNombre1;
    private javax.swing.JLabel ResLablePresupuesto1;
    private javax.swing.JLabel ResLableTelefono1;
    private javax.swing.JLabel ResLableTipoCatering1;
    private static javax.swing.JTextField ResTextApellido1;
    private static javax.swing.JTextField ResTextApellido2;
    private static javax.swing.JTextField ResTextAsistentes;
    private static javax.swing.JTextField ResTextBar;
    private static javax.swing.JTextField ResTextCatering;
    private static javax.swing.JTextField ResTextEscape;
    private static javax.swing.JTextField ResTextFecha;
    private static javax.swing.JTextField ResTextInvitados;
    private static javax.swing.JTextField ResTextNombre;
    private static javax.swing.JTextField ResTextNumeroTel;
    private static javax.swing.JTextField ResTextPresupuesto;
    private javax.swing.JPanel Resultado;
    private javax.swing.JTabbedPane menu;
    // End of variables declaration//GEN-END:variables
}
