server.port = 8501
spring.application.name = saludo
springdoc.api-docs.path = /api-saludot

spring.datasource.url=jdbc:mysql://localhost:3306/empleadosbd504?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=abc123.
spring.jpa.hibernate.ddl-auto=update