server.port = 8503
spring.application.name = productos
springdoc.api-docs.path = /api-productos

spring.datasource.url=jdbc:mysql://localhost:3306/empleadosbd504?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=abc123.
spring.jpa.hibernate.ddl-auto=update